name: React build apple

on: 
  push:            
    branches:
      - main

jobs:
  React-Build-ssh-action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4        
        with:
          host: ${{ secrets.HOST }}          
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 40s  # 30초 기본        
          script: |
            cd sh-zip
            sh restart-api-docs.sh
            
